// Generated by Wrangler on Wed Jul 31 2024 14:34:46 GMT+0800 (Hong Kong Standard Time)
// by running `wrangler types`

interface Env {
	DELETE_TOKEN_HASH: string;
	COUNTER: DurableObjectNamespace<import("./src/index").Counter>;
}
